# Generated by Django 6.0.5 on 2026-05-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agent_setup_prompt_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
