# Generated by Django 6.0.6 on 2026-06-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_agentapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentapikey",
            name="token_ciphertext",
            field=models.TextField(blank=True, default=""),
        ),
    ]
