# Generated by Django 6.0.6 on 2026-06-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agentapikey_token_ciphertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapikey',
            name='access_level',
            field=models.CharField(choices=[('read', 'Read'), ('read_write', 'Read + write'), ('admin', 'Admin')], default='read_write', max_length=20),
        ),
    ]
