# Generated by Django 6.0.6 on 2026-06-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agentapikey_access_level'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentapikey',
            name='unique_agent_api_key_name_per_profile',
        ),
        migrations.AddConstraint(
            model_name='agentapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('profile', 'name'), name='unique_agent_api_key_name_per_profile'),
        ),
    ]
