# Generated by Django 6.0.6 on 2026-07-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agentapikey_unique_agent_api_key_name_per_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='agent_api_key',
            field=models.ForeignKey(blank=True, help_text='The agent API key used to submit the feedback, when available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='core.agentapikey'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Optional structured context supplied with the feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(choices=[('browser', 'Browser'), ('api', 'REST API'), ('mcp', 'MCP')], default='browser', help_text='The interface that submitted the feedback', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='page',
            field=models.CharField(blank=True, default='', help_text='The page where the feedback was submitted', max_length=255),
        ),
    ]
