# Generated by Django 6.0.6 on 2026-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_feedback_agent_api_key_feedback_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="choice_colorization_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Render choice values with color accents in the dataset UI.",
            ),
        ),
    ]
