# Generated by Django 6.0.6 on 2026-07-13 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_profile_choice_colorization_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("trial_ends_at__isnull", True), ("trial_started_at__isnull", True)),
                    models.Q(
                        ("trial_ends_at__gte", models.F("trial_started_at")),
                        ("trial_ends_at__isnull", False),
                        ("trial_started_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="profile_trial_dates_both_set_or_empty",
            ),
        ),
    ]
