# Generated by Django 6.0.6 on 2026-07-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_profile_trial_ends_at_profile_trial_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="setup_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
