# Generated by Django 6.0.6 on 2026-07-15 12:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_profile_setup_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialRewardClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reward",
                    models.CharField(
                        choices=[
                            ("email_verified", "Email verified"),
                            ("github_star", "GitHub star"),
                            ("discord_join", "Discord community"),
                            ("x_follow", "X follow"),
                        ],
                        max_length=32,
                    ),
                ),
                ("days", models.PositiveSmallIntegerField(default=3)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_reward_claims",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "reward"), name="unique_trial_reward_per_profile"
                    )
                ],
            },
        ),
    ]
