# Generated by Django 6.0.6 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_trialrewardclaim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="choice_colorization_enabled",
            field=models.BooleanField(
                default=True, help_text="Render choice values with color accents in the dataset UI."
            ),
        ),
    ]
