# Generated by Django 6.0.6 on 2026-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_profile_choice_colorization_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="marketing_attribution",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sanitized first- and latest-touch campaign attribution.",
            ),
        ),
    ]
