# Generated by Django 6.0.6 on 2026-07-03 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
