# Generated by Django 6.0.6 on 2026-06-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcpoauthaccesstoken',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='mcpoauthauthorizationcode',
            name='profile',
        ),
        migrations.DeleteModel(
            name='McpOAuthAuthorizationRequest',
        ),
        migrations.DeleteModel(
            name='McpOAuthClient',
        ),
        migrations.RemoveField(
            model_name='mcpoauthrefreshtoken',
            name='profile',
        ),
        migrations.DeleteModel(
            name='McpOAuthAccessToken',
        ),
        migrations.DeleteModel(
            name='McpOAuthAuthorizationCode',
        ),
        migrations.DeleteModel(
            name='McpOAuthRefreshToken',
        ),
    ]
