"""
Django settings for rowset project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import logging
import os
import re
import sys
from pathlib import Path

import environ
import sentry_sdk
import structlog
from django.core.exceptions import ImproperlyConfigured
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from structlog_sentry import SentryProcessor

from rowset.sentry_metrics import install_sentry_metrics_middleware
from rowset.sentry_utils import CustomLoggingIntegration, before_send

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(BASE_DIR / ".env")

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)


def _split_env_urls(value: str) -> tuple[str, ...]:
    urls = []
    for line in str(value or "").replace(",", "\n").splitlines():
        url = line.strip()
        if url:
            urls.append(url)
    return tuple(urls)


def _production_configuration_error(variable: str, reason: str) -> None:
    raise ImproperlyConfigured(f"Invalid {variable}: {reason}.")


def _validate_production_secret(
    variable: str,
    value: str,
    *,
    minimum_length: int,
    development_default: str,
) -> None:
    if value == development_default:
        _production_configuration_error(variable, "uses an unsafe development default")
    if len(value) < minimum_length:
        _production_configuration_error(
            variable,
            f"must contain at least {minimum_length} characters",
        )
    if "\n" in value or "\r" in value:
        _production_configuration_error(variable, "must be a single line")
    if not re.fullmatch(r"[A-Za-z0-9._~-]+", value):
        _production_configuration_error(
            variable,
            "must use only safe characters: letters, numbers, dot, underscore, tilde, or hyphen",
        )


def _validate_production_configuration() -> None:
    if DEBUG:
        _production_configuration_error("DEBUG", "must be off")
    if not ROWSET_INSECURE_HTTP and not SITE_URL.startswith("https://"):
        _production_configuration_error("SITE_URL", "must use https")

    _validate_production_secret(
        "SECRET_KEY",
        SECRET_KEY,
        minimum_length=50,
        development_default="super-secret-key",
    )
    _validate_production_secret(
        "POSTGRES_PASSWORD",
        POSTGRES_PASSWORD,
        minimum_length=32,
        development_default="rowset",
    )
    _validate_production_secret(
        "REDIS_PASSWORD",
        REDIS_PASSWORD,
        minimum_length=32,
        development_default="rowset",
    )

    if len({SECRET_KEY, POSTGRES_PASSWORD, REDIS_PASSWORD}) != 3:
        _production_configuration_error("SECRETS", "must be distinct")

    for fallback in SECRET_KEY_FALLBACKS:
        _validate_production_secret(
            "SECRET_KEY_FALLBACKS",
            fallback,
            minimum_length=50,
            development_default="super-secret-key",
        )
        if fallback == SECRET_KEY:
            _production_configuration_error(
                "SECRET_KEY_FALLBACKS",
                "must not repeat the active key",
            )


# Options: dev, prod
ENVIRONMENT = env("ENVIRONMENT")

SENTRY_DSN = env("SENTRY_DSN", default="")
SENTRY_RELEASE = env("SENTRY_RELEASE", default="")
SENTRY_TRACES_SAMPLE_RATE = env.float("SENTRY_TRACES_SAMPLE_RATE", default=1.0)
SENTRY_PROFILE_SESSION_SAMPLE_RATE = env.float("SENTRY_PROFILE_SESSION_SAMPLE_RATE", default=1.0)
SENTRY_ENABLE_LOGS = env.bool("SENTRY_ENABLE_LOGS", default=True)
SENTRY_ENABLE_METRICS = env.bool("SENTRY_ENABLE_METRICS", default=True)
SENTRY_SEND_DEFAULT_PII = env.bool("SENTRY_SEND_DEFAULT_PII", default=False)
SENTRY_INCLUDE_LOCAL_VARIABLES = env.bool("SENTRY_INCLUDE_LOCAL_VARIABLES", default=False)
SENTRY_MAX_BREADCRUMBS = env.int("SENTRY_MAX_BREADCRUMBS", default=100)

POSTHOG_API_KEY = env("POSTHOG_API_KEY", default="")
POSTHOG_HOST = env("POSTHOG_HOST", default="https://us.i.posthog.com").rstrip("/")
POSTHOG_BROWSER_HOST = (env("POSTHOG_BROWSER_HOST", default="") or POSTHOG_HOST).rstrip("/")
POSTHOG_LOGS_ENDPOINT = f"{POSTHOG_HOST}/i/v1/logs"
POSTHOG_LOGS_ENABLED = env.bool(
    "POSTHOG_LOGS_ENABLED",
    default=ENVIRONMENT == "prod" and bool(POSTHOG_API_KEY),
)
POSTHOG_LOG_LEVEL = env("POSTHOG_LOG_LEVEL", default="INFO")
POSTHOG_PROCESS_TYPE = env(
    "APP_PROCESS_TYPE",
    default="worker" if "qcluster" in sys.argv else "server",
)
POSTHOG_DEFAULT_PROCESS_NAME = "worker" if POSTHOG_PROCESS_TYPE == "worker" else "web"
POSTHOG_SERVICE_NAME = (
    env("POSTHOG_SERVICE_NAME", default=f"rowset-{POSTHOG_DEFAULT_PROCESS_NAME}")
    or f"rowset-{POSTHOG_DEFAULT_PROCESS_NAME}"
)
POSTHOG_SERVICE_VERSION = SENTRY_RELEASE or env("RENDER_GIT_COMMIT", default="") or "unknown"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
SECRET_KEY_FALLBACKS = env.list("SECRET_KEY_FALLBACKS", default=[])

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

SITE_URL = env("SITE_URL")
ROWSET_INSECURE_HTTP = env.bool("ROWSET_INSECURE_HTTP", default=False)
PRODUCTION_HTTPS_ENABLED = ENVIRONMENT == "prod" and not ROWSET_INSECURE_HTTP

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if PRODUCTION_HTTPS_ENABLED else None
SECURE_SSL_REDIRECT = PRODUCTION_HTTPS_ENABLED
SESSION_COOKIE_SECURE = PRODUCTION_HTTPS_ENABLED
CSRF_COOKIE_SECURE = PRODUCTION_HTTPS_ENABLED
SECURE_HSTS_SECONDS = 31_536_000 if PRODUCTION_HTTPS_ENABLED else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
DATA_UPLOAD_MAX_MEMORY_SIZE = 64_000_000

# Rowset secures its own hostname without imposing HSTS policy on sibling subdomains.
SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]

TRIAL_DURATION_DAYS = 7
SITE_HOST = SITE_URL.replace("http://", "").replace("https://", "").split("/")[0].split(":")[0]
BLOG_POSTS_DIR = BASE_DIR / "apps" / "pages" / "content" / "blog"

# Keep production locked to the configured site hostname.
ALLOWED_HOSTS = [SITE_HOST]
CSRF_TRUSTED_ORIGINS = [SITE_URL]

if DEBUG:
    # Local integration work often runs through ephemeral tunnel hostnames.
    ALLOWED_HOSTS = ["*"]
    CSRF_TRUSTED_ORIGINS = [
        SITE_URL,
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://backend:8000",
        "https://*.ngrok-free.app",
        "https://*.ngrok.app",
        "https://*.trycloudflare.com",
        "https://*.loca.lt",
    ]

DEFAULT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
]

THIRD_PARTY_APPS = [
    "widget_tweaks",
    "anymail",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "allauth.mfa",
    "django_htmx",
    "django_q",
    "mjml",
    "django_structlog",
]

if ENVIRONMENT == "dev":
    THIRD_PARTY_APPS.append("django_extensions")

CUSTOM_APPS = [
    "apps.core.CoreConfig",
    "apps.api.ApiConfig",
    "apps.mcp_server.apps.McpServerConfig",
    "apps.datasets.apps.DatasetsConfig",
    "apps.pages.PagesConfig",
]

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.pages.middleware.SearchEngineIndexingMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "rowset.request_logging.RequestLoggingMiddleware",
    "apps.core.middleware.AgentSetupCompletionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_structlog.middlewares.RequestMiddleware",
    "posthog.integrations.django.PosthogContextMiddleware",
]

if SENTRY_DSN and ENVIRONMENT == "prod" and SENTRY_ENABLE_METRICS:
    install_sentry_metrics_middleware(MIDDLEWARE)

ROOT_URLCONF = "rowset.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("frontend", "templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.app_navigation",
                "apps.core.context_processors.current_state",
                "apps.core.context_processors.posthog_api_key",
                "apps.core.context_processors.chatwoot_config",
                "apps.core.context_processors.mjml_url",
                "apps.core.context_processors.available_social_providers",
                "apps.pages.context_processors.referrer_banner",
                "apps.pages.context_processors.social_metadata",
                "apps.pages.context_processors.search_metadata",
            ],
        },
    },
]

WSGI_APPLICATION = "rowset.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

POSTGRES_DB = env("POSTGRES_DB")
POSTGRES_USER = env("POSTGRES_USER")
POSTGRES_PASSWORD = env("POSTGRES_PASSWORD")
POSTGRES_HOST = env("POSTGRES_HOST")
POSTGRES_PORT = env("POSTGRES_PORT", default="5432")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRES_DB,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": POSTGRES_HOST,
        "PORT": POSTGRES_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR.joinpath("static/")

STATICFILES_DIRS = [
    BASE_DIR.joinpath("frontend/build"),
]

asset_s3_endpoint_url = env(
    "ROWSET_ASSET_S3_ENDPOINT_URL",
    default="",
).strip()
asset_storage_bucket_name = env(
    "ROWSET_ASSET_STORAGE_BUCKET_NAME",
    default=("rowset-assets-dev" if ENVIRONMENT == "dev" else ""),
).strip()
asset_access_key = env("ROWSET_ASSET_ACCESS_KEY_ID", default="").strip()
asset_secret_key = env("ROWSET_ASSET_SECRET_ACCESS_KEY", default="").strip()
asset_region_name = env("ROWSET_ASSET_REGION_NAME", default="auto")

MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
PRIVATE_MEDIA_ROOT = BASE_DIR.joinpath("private_media")

MEDIA_URL = "/media/"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if not asset_s3_endpoint_url:
    STORAGES["dataset_assets"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": str(PRIVATE_MEDIA_ROOT),
        },
    }
else:
    if not asset_storage_bucket_name:
        raise ImproperlyConfigured(
            "ROWSET_ASSET_STORAGE_BUCKET_NAME must be set when private dataset "
            "asset storage uses an S3-compatible endpoint."
        )
    if not asset_access_key:
        raise ImproperlyConfigured(
            "ROWSET_ASSET_ACCESS_KEY_ID must be set when private dataset "
            "asset storage uses an S3-compatible endpoint."
        )
    if not asset_secret_key:
        raise ImproperlyConfigured(
            "ROWSET_ASSET_SECRET_ACCESS_KEY must be set when private dataset "
            "asset storage uses an S3-compatible endpoint."
        )

    STORAGES["dataset_assets"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": asset_storage_bucket_name,
            "default_acl": "private",
            "region_name": asset_region_name,
            "endpoint_url": asset_s3_endpoint_url,
            "access_key": asset_access_key,
            "secret_key": asset_secret_key,
            "querystring_auth": True,
            "file_overwrite": False,
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "landing"

ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False
# Send verification email during signup, but do not block the new user's first session.
# Users land in the app immediately and see an in-app reminder until they verify.
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = False
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ALLOW_SIGNUPS = env.bool("ALLOW_SIGNUPS", default=True)
ACCOUNT_FORMS = {
    "signup": "apps.core.forms.CustomSignUpForm",
    "login": "apps.core.forms.CustomLoginForm",
}
ACCOUNT_ADAPTER = "rowset.adapters.CustomAccountAdapter"
if PRODUCTION_HTTPS_ENABLED:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# Passkey (WebAuthn) auth support via django-allauth MFA.
MFA_SUPPORTED_TYPES = ["webauthn"]
MFA_PASSKEY_LOGIN_ENABLED = True
# allauth requires mandatory code-based email verification for passkey signup.
# Keep password signup non-blocking instead of sending new users to the raw code page.
MFA_PASSKEY_SIGNUP_ENABLED = False
# Local dev uses http://localhost, so allow insecure origin only in debug.
MFA_WEBAUTHN_ALLOW_INSECURE_ORIGIN = DEBUG

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_STORE_TOKENS = True
SOCIALACCOUNT_PROVIDERS = {}
SOCIALACCOUNT_ADAPTER = "rowset.adapters.CustomSocialAccountAdapter"

GITHUB_CLIENT_ID = env("GITHUB_CLIENT_ID", default="")
if GITHUB_CLIENT_ID != "":
    SOCIALACCOUNT_PROVIDERS["github"] = {
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
        "AUTO_SIGNUP": True,
        "APP": {
            "client_id": env("GITHUB_CLIENT_ID"),
            "secret": env("GITHUB_CLIENT_SECRET"),
        },
    }

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET", default="")
if GOOGLE_CLIENT_ID != "":
    SOCIALACCOUNT_PROVIDERS["google"] = {
        "SCOPE": [
            "profile",
            "email",
        ],
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
        "AUTO_SIGNUP": True,
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
        },
    }

MAILGUN_API_KEY = env("MAILGUN_API_KEY", default="")
MAILGUN_SENDER_DOMAIN = env("MAILGUN_SENDER_DOMAIN", default="mg.lvtd.dev")
ANYMAIL = {
    "MAILGUN_API_KEY": MAILGUN_API_KEY,
    "MAILGUN_SENDER_DOMAIN": MAILGUN_SENDER_DOMAIN,
}
DEFAULT_FROM_EMAIL = "Rasul Kireev <rasul@lvtd.dev>"
SERVER_EMAIL = "Rowset Errors <rasul@lvtd.dev>"

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "mailhog"  # Use the service name from docker-compose
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
else:
    if MAILGUN_API_KEY == "":
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"

EMAIL_DELIVERY_RETRY_BACKOFF_SECONDS = (0.0, 1.0, 3.0)

REDIS_HOST = env("REDIS_HOST", default="localhost")
REDIS_PORT = env("REDIS_PORT", default="6379")
REDIS_PASSWORD = env("REDIS_PASSWORD", default="")
REDIS_DB = env("REDIS_DB", default="0")
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

if ENVIRONMENT == "prod":
    _validate_production_configuration()

Q_CLUSTER = {
    "name": "rowset-q",
    "timeout": 3600,  # 1 hour
    "retry": 4800,  # 80 minutes
    "workers": 4,
    "max_attempts": 2,
    "redis": REDIS_URL,
    "error_reporter": {},
}


def extract_from_record(logger, name, event_dict):
    """
    Extract thread name and add them to the event dict.
    """
    record = event_dict["_record"]
    event_dict["thread_id"] = record.thread
    return event_dict


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "json": {"format": "%(message)s"},
        "json_formatter": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processors": [
                extract_from_record,
                structlog.stdlib.ProcessorFormatter.remove_processors_meta,
                structlog.processors.JSONRenderer(),
            ],
        },
        "plain_console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
        "key_value": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.KeyValueRenderer(
                key_order=["timestamp", "level", "event", "logger"]
            ),
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "prod_console": {
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "json_console": {
            "class": "logging.StreamHandler",
            "formatter": "json_formatter",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "django_structlog": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        # django.server can log some low-level logs, but also does log requests,
        # for some reason...
        "django.server": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",  # so we don't chunder 404s, etc
            "propagate": False,
        },
        "rowset": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
    },
}

if POSTHOG_LOGS_ENABLED and POSTHOG_API_KEY:
    LOGGING["handlers"]["posthog"] = {
        "()": "rowset.posthog_logging.PostHogLoggingHandler",
        "level": POSTHOG_LOG_LEVEL,
        "endpoint": POSTHOG_LOGS_ENDPOINT,
        "api_key": POSTHOG_API_KEY,
        "service_name": POSTHOG_SERVICE_NAME,
        "environment": ENVIRONMENT,
        "service_version": POSTHOG_SERVICE_VERSION,
    }
    LOGGING["loggers"]["rowset"]["handlers"].append("posthog")

structlog_processors = [
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.filter_by_level,
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.StackInfoRenderer(),
    # structlog.processors.format_exc_info,
]

if SENTRY_DSN and ENVIRONMENT == "prod":
    structlog_processors.append(
        SentryProcessor(
            event_level=logging.ERROR,
            level=logging.INFO,
            active=True,
            as_context=True,
            tag_keys="__all__",
            verbose=True,
        )
    )


structlog_processors.extend(
    [
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ]
)

structlog.configure(
    processors=structlog_processors,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

if ENVIRONMENT == "prod":
    LOGGING["loggers"]["django.server"]["level"] = "WARNING"
    LOGGING["loggers"]["django_structlog"]["handlers"].append("json_console")
    LOGGING["loggers"]["rowset"]["level"] = env("DJANGO_LOG_LEVEL", default="INFO")
    LOGGING["loggers"]["rowset"]["handlers"].append("json_console")

if SENTRY_DSN and ENVIRONMENT == "prod":
    Q_CLUSTER["error_reporter"]["sentry"] = {"dsn": SENTRY_DSN}
    sentry_sdk.init(
        debug=DEBUG,
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        release=SENTRY_RELEASE or None,
        send_default_pii=SENTRY_SEND_DEFAULT_PII,
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        profile_session_sample_rate=SENTRY_PROFILE_SESSION_SAMPLE_RATE,
        profile_lifecycle="trace",
        enable_logs=SENTRY_ENABLE_LOGS,
        max_breadcrumbs=SENTRY_MAX_BREADCRUMBS,
        integrations=[
            DjangoIntegration(),
            RedisIntegration(),
            CustomLoggingIntegration(level=logging.INFO, event_level=logging.ERROR),
        ],
        before_send=before_send,
        attach_stacktrace=True,
        include_local_variables=SENTRY_INCLUDE_LOCAL_VARIABLES,
    )

CHATWOOT_BASE_URL = env("CHATWOOT_BASE_URL", default="")
CHATWOOT_WEBSITE_TOKEN = env("CHATWOOT_WEBSITE_TOKEN", default="")
CHATWOOT_HMAC_SECRET = env("CHATWOOT_HMAC_SECRET", default="")

ROWSET_FEEDBACK_APPRISE_URLS = _split_env_urls(env("ROWSET_FEEDBACK_APPRISE_URLS", default=""))
ROWSET_FEEDBACK_APPRISE_TITLE = env("ROWSET_FEEDBACK_APPRISE_TITLE", default="New Rowset feedback")


BUTTONDOWN_API_KEY = env("BUTTONDOWN_API_KEY", default="")


STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
STRIPE_CONTEXT = env("STRIPE_CONTEXT", default="")
STRIPE_LIVE_MODE = ENVIRONMENT == "prod"
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_WEBHOOK_UUID = env("WEBHOOK_UUID", default="")
STRIPE_PRICE_ID_ROWSET_PRO_MONTHLY = env("STRIPE_PRICE_ID_ROWSET_PRO_MONTHLY", default="")
STRIPE_PRICE_IDS = {
    "monthly": STRIPE_PRICE_ID_ROWSET_PRO_MONTHLY,
}

QDRANT_URL = env("QDRANT_URL", default="")
QDRANT_API_KEY = env("QDRANT_API_KEY", default="")
QDRANT_TIMEOUT_SECONDS = env.int("QDRANT_TIMEOUT_SECONDS", default=10)
QDRANT_COLLECTION_PREFIX = env("QDRANT_COLLECTION_PREFIX", default="rowset")
ROWSET_VECTOR_SEARCH_ENABLED = env.bool("ROWSET_VECTOR_SEARCH_ENABLED", default=False)
ROWSET_EMBEDDING_MODEL = env("ROWSET_EMBEDDING_MODEL", default="openai/text-embedding-3-small")
ROWSET_EMBEDDING_DIMENSIONS = env.int("ROWSET_EMBEDDING_DIMENSIONS", default=1536)
OPENROUTER_BASE_URL = env("OPENROUTER_BASE_URL", default="https://openrouter.ai/api/v1")
OPENROUTER_API_KEY = env("OPENROUTER_API_KEY", default="")
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")


MJML_BACKEND_MODE = "httpserver"
MJML_URL = env("MJML_URL", default="")
MJML_HTTPSERVERS = [
    {
        "URL": f"{MJML_URL}/v1/render",
    }
]


SHELL_PLUS_IMPORTS = [
    "from django_q.tasks import async_task",
    "from apps.core.tasks import *",
]
